/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 47

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TileLabelBank 0


/* Gameboy Color palette 0 */
#define TileLabelCGBPal0c0 0
#define TileLabelCGBPal0c1 1023
#define TileLabelCGBPal0c2 32767
#define TileLabelCGBPal0c3 31744

/* Gameboy Color palette 1 */
#define TileLabelCGBPal1c0 0
#define TileLabelCGBPal1c1 1023
#define TileLabelCGBPal1c2 191
#define TileLabelCGBPal1c3 32767

/* Gameboy Color palette 2 */
#define TileLabelCGBPal2c0 0
#define TileLabelCGBPal2c1 1023
#define TileLabelCGBPal2c2 32767
#define TileLabelCGBPal2c3 32421

/* Gameboy Color palette 3 */
#define TileLabelCGBPal3c0 0
#define TileLabelCGBPal3c1 1023
#define TileLabelCGBPal3c2 32767
#define TileLabelCGBPal3c3 31744

/* Gameboy Color palette 4 */
#define TileLabelCGBPal4c0 0
#define TileLabelCGBPal4c1 1023
#define TileLabelCGBPal4c2 32767
#define TileLabelCGBPal4c3 31744

/* Gameboy Color palette 5 */
#define TileLabelCGBPal5c0 0
#define TileLabelCGBPal5c1 1023
#define TileLabelCGBPal5c2 32767
#define TileLabelCGBPal5c3 31744

/* Gameboy Color palette 6 */
#define TileLabelCGBPal6c0 0
#define TileLabelCGBPal6c1 1023
#define TileLabelCGBPal6c2 32767
#define TileLabelCGBPal6c3 31744

/* Gameboy Color palette 7 */
#define TileLabelCGBPal7c0 0
#define TileLabelCGBPal7c1 1023
#define TileLabelCGBPal7c2 32767
#define TileLabelCGBPal7c3 31744
/* CGBpalette entries. */
extern unsigned char TileLabelCGB[];
/* Start of tile array. */
extern unsigned char TileLabel[];

/* End of EXPORT.H */
