/*

 PACTEXT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TextTileBank 0


/* Gameboy Color palette 0 */
#define TextTileCGBPal0c0 0
#define TextTileCGBPal0c1 0
#define TextTileCGBPal0c2 0
#define TextTileCGBPal0c3 4093

/* Gameboy Color palette 1 */
#define TextTileCGBPal1c0 0
#define TextTileCGBPal1c1 0
#define TextTileCGBPal1c2 0
#define TextTileCGBPal1c3 31744

/* Gameboy Color palette 2 */
#define TextTileCGBPal2c0 0
#define TextTileCGBPal2c1 0
#define TextTileCGBPal2c2 0
#define TextTileCGBPal2c3 32767

/* Gameboy Color palette 3 */
#define TextTileCGBPal3c0 0
#define TextTileCGBPal3c1 8935
#define TextTileCGBPal3c2 6596
#define TextTileCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TextTileCGBPal4c0 0
#define TextTileCGBPal4c1 8935
#define TextTileCGBPal4c2 6596
#define TextTileCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TextTileCGBPal5c0 0
#define TextTileCGBPal5c1 8935
#define TextTileCGBPal5c2 6596
#define TextTileCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TextTileCGBPal6c0 0
#define TextTileCGBPal6c1 8935
#define TextTileCGBPal6c2 6596
#define TextTileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TextTileCGBPal7c0 0
#define TextTileCGBPal7c1 8935
#define TextTileCGBPal7c2 6596
#define TextTileCGBPal7c3 5344


/* Start of tile array. */
const extern unsigned char TextTile[];

/* End of PACTEXT.H */
