/*

 SPLASHTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 140

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Gameboy Color palette 0 */
#define SplashTileCGBPal0c0 2048
#define SplashTileCGBPal0c1 8192
#define SplashTileCGBPal0c2 16846
#define SplashTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SplashTileCGBPal1c0 13278
#define SplashTileCGBPal1c1 4095
#define SplashTileCGBPal1c2 33
#define SplashTileCGBPal1c3 8952

/* Gameboy Color palette 2 */
#define SplashTileCGBPal2c0 5318
#define SplashTileCGBPal2c1 3171
#define SplashTileCGBPal2c2 7399
#define SplashTileCGBPal2c3 0

/* Gameboy Color palette 3 */
#define SplashTileCGBPal3c0 15887
#define SplashTileCGBPal3c1 30653
#define SplashTileCGBPal3c2 8423
#define SplashTileCGBPal3c3 0

/* Gameboy Color palette 4 */
#define SplashTileCGBPal4c0 4096
#define SplashTileCGBPal4c1 9216
#define SplashTileCGBPal4c2 15393
#define SplashTileCGBPal4c3 0

/* Gameboy Color palette 5 */
#define SplashTileCGBPal5c0 24311
#define SplashTileCGBPal5c1 32767
#define SplashTileCGBPal5c2 8455
#define SplashTileCGBPal5c3 0

/* Gameboy Color palette 6 */
#define SplashTileCGBPal6c0 6143
#define SplashTileCGBPal6c1 3666
#define SplashTileCGBPal6c2 231
#define SplashTileCGBPal6c3 0

/* Gameboy Color palette 7 */
#define SplashTileCGBPal7c0 14369
#define SplashTileCGBPal7c1 8192
#define SplashTileCGBPal7c2 19489
#define SplashTileCGBPal7c3 1024
/* CGBpalette entries. */
extern unsigned char SplashTileCGB[];
/* Start of tile array. */
extern unsigned char SplashTile[];

/* End of SPLASHTILES.H */
