/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SpriteBank 0

/* Super Gameboy palette 0 */
#define SpriteSGBPal0c0 6076
#define SpriteSGBPal0c1 8935
#define SpriteSGBPal0c2 6596
#define SpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpriteSGBPal1c0 6076
#define SpriteSGBPal1c1 8935
#define SpriteSGBPal1c2 6596
#define SpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpriteSGBPal2c0 6076
#define SpriteSGBPal2c1 8935
#define SpriteSGBPal2c2 6596
#define SpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpriteSGBPal3c0 6076
#define SpriteSGBPal3c1 8935
#define SpriteSGBPal3c2 6596
#define SpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpriteCGBPal0c0 32767
#define SpriteCGBPal0c1 0
#define SpriteCGBPal0c2 22197
#define SpriteCGBPal0c3 4095

/* Gameboy Color palette 1 */
#define SpriteCGBPal1c0 32767
#define SpriteCGBPal1c1 1023
#define SpriteCGBPal1c2 0
#define SpriteCGBPal1c3 32008

/* Gameboy Color palette 2 */
#define SpriteCGBPal2c0 32767
#define SpriteCGBPal2c1 0
#define SpriteCGBPal2c2 0
#define SpriteCGBPal2c3 32569

/* Gameboy Color palette 3 */
#define SpriteCGBPal3c0 32767
#define SpriteCGBPal3c1 32767
#define SpriteCGBPal3c2 32767
#define SpriteCGBPal3c3 32767

/* Gameboy Color palette 4 */
#define SpriteCGBPal4c0 32767
#define SpriteCGBPal4c1 32767
#define SpriteCGBPal4c2 32767
#define SpriteCGBPal4c3 32767

/* Gameboy Color palette 5 */
#define SpriteCGBPal5c0 32767
#define SpriteCGBPal5c1 32767
#define SpriteCGBPal5c2 32767
#define SpriteCGBPal5c3 32767

/* Gameboy Color palette 6 */
#define SpriteCGBPal6c0 32767
#define SpriteCGBPal6c1 32767
#define SpriteCGBPal6c2 32767
#define SpriteCGBPal6c3 32767

/* Gameboy Color palette 7 */
#define SpriteCGBPal7c0 32767
#define SpriteCGBPal7c1 32767
#define SpriteCGBPal7c2 32767
#define SpriteCGBPal7c3 32767
/* CGBpalette entries. */
extern unsigned char SpriteCGB[];
/* Start of tile array. */
extern unsigned char Sprite[];

/* End of SPRITES.H */
