/*

 TEXTDATA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\Pacman\tile and gfx\pactext.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TextTileDataWidth 20
#define TextTileDataHeight 18
#define TextTileDataBank 0

const extern unsigned char TextTileData[];

#define TextTilePaletteWidth 20
#define TextTilePaletteHeight 18
#define TextTilePaletteBank 0

const extern unsigned char TextTileCGB[];

/* End of TEXTDATA.H */
